import { useEffect, useMemo, useRef, useState } from 'react';
import { Steps } from 'antd';
import UploadDropzone from './UploadDropzone.jsx';
import LoadingState from './LoadingState.jsx';
import MapPanel from './MapPanel.jsx';
import ResultsSummary from './ResultsSummary.jsx';
import PhotoDossier from './PhotoDossier.jsx';
import StatusChip from './StatusChip.jsx';
import { buildCoordinateExport, downloadCoordinateExport } from '../features/export/coordinateExport.js';
import { PROCESSING_STEPS, canAdvanceProcessingStep, canEnterProcessingStep, completeProcessingStep, createProcessingWorkflowState, deriveProcessingReadiness, invalidateProcessingAfter, invalidateProcessingFrom, moveProcessingStep, nextProcessingStep } from '../features/ui/processingWorkflow.js';

const attention = (p) => !p?.coordinates || !String(p?.indexFromOcr||'').trim() || ['failed','error','missing'].includes(String(p?.gpsStatus||'').toLowerCase()) || ['failed','error','missing'].includes(String(p?.ocrStatus||'').toLowerCase()) || ['low_precision','suspicious','missing'].includes(p?.coordinateQuality) || Boolean(p?.userError);
const reserve = (p) => String(p?.workStatus || p?.disposition || '').toLowerCase() === 'reserve';
const initialStep = (photos) => { const r=deriveProcessingReadiness(photos); if(r.upload||r.result)return 'result'; if(photos.some((p)=>['processing','done','failed','skipped'].includes(p.cleanupStatus)||['processing','done','failed','skipped'].includes(p.uploadStatus)))return 'upload'; if(r.recognition)return 'map'; return r.photos?'recognition':'photos'; };

export default function ProcessingWorkflow(props) {
  const { photos, session, mode, errors=[], providerValidation, providerSettings, thresholdMeters, mapLayerId, recommendation, folderImport, isBusy }=props;
  const r=useMemo(()=>deriveProcessingReadiness(photos),[photos]);
  const [wf,setWf]=useState(()=>createProcessingWorkflowState(initialStep(photos), session?.processingWorkflow));
  const [dossier,setDossier]=useState({open:false,photoId:'',context:'recognition'});
  const [recognitionShowAll,setRecognitionShowAll]=useState(false);
  const [uploadShowAll,setUploadShowAll]=useState(false);
  const batchRef=useRef(photos.map((p)=>String(p.id)).join('|')); const mountedRef=useRef(false); const signature=photos.map((p)=>String(p.id)).join('|');
  useEffect(()=>{ if(!mountedRef.current){mountedRef.current=true;batchRef.current=signature;return;} const prev=batchRef.current; if(prev!==signature){setWf(createProcessingWorkflowState('photos'));setDossier({open:false,photoId:'',context:'recognition'});} batchRef.current=signature; },[signature]);
  useEffect(()=>setWf((current)=>{let next=current; ['photos','recognition','upload'].forEach((step)=>{if(r[step]&&!next.completed.includes(step))next=completeProcessingStep(next,step);}); return next;}),[r.photos,r.recognition,r.upload]);
  useEffect(()=>{ props.onSessionChange?.({ processingWorkflow: wf, stage: wf.current==='result'?'result':wf.current==='upload'?'upload':'processing' }); },[wf]);
  const current=wf.current; const selected=photos.find((p)=>String(p.id)===String(dossier.photoId))||null;
  const go=(id)=>setWf((s)=>moveProcessingStep(s,id,r));
  const advance=()=>{if(current!=='map'&&!canAdvanceProcessingStep(current,r))return; if(current==='map'&&!r.canEnterMap)return; const nextId=nextProcessingStep(current); setWf((s)=>{const done=completeProcessingStep(s,current); return nextId?{...moveProcessingStep(done,nextId,r),current:nextId}:done;});};
  const invalidate=(step)=>setWf((s)=>invalidateProcessingAfter(s,step));
  const runRecognition=()=>{setWf((s)=>invalidateProcessingFrom(s,'recognition'));return props.onRun?.({gps:true,cleanup:false,upload:false},'Распознавание координат');};
  const runUpload=()=>{setWf((s)=>invalidateProcessingFrom(s,'upload'));return props.onRun?.({gps:false,cleanup:true,upload:true},'Очистка и загрузка');};
  const applyIndex=(...a)=>{const ok=props.onApplyIndex?.(...a);if(ok!==false)invalidate('recognition');return ok;};
  const applyCoords=(...a)=>{const ok=props.onApplyCoordinates?.(...a);if(ok!==false)invalidate('recognition');return ok;};
  const swap=(...a)=>{const ok=props.onSwapCoordinates?.(...a);if(ok!==false)invalidate('recognition');return ok;};
  const toggleReserve=(...a)=>{props.onToggleReserve?.(...a);invalidate('map');};
  const openDossier=(photoId,context=current)=>setDossier({open:true,photoId,context});
  const rows=useMemo(()=>[...photos].sort((a,b)=>Number(attention(b))-Number(attention(a))||(a.number||0)-(b.number||0)),[photos]);
  const recognitionIssues=rows.filter(attention);
  const visibleRows=recognitionIssues.length>0&&!recognitionShowAll?recognitionIssues:rows;
  const active=photos.filter((p)=>!reserve(p));
  const uploadRows=[...active].sort((a,b)=>Number(Boolean(b.userError||b.cleanupStatus==='failed'||b.uploadStatus==='failed'))-Number(Boolean(a.userError||a.cleanupStatus==='failed'||a.uploadStatus==='failed')));
  const uploadIssues=uploadRows.filter((p)=>Boolean(p.userError||p.cleanupStatus==='failed'||p.uploadStatus==='failed'||(p.uploadStatus==='done'&&!(p.uploadResult?.links||[]).length)));
  const visibleUploadRows=uploadIssues.length>0&&!uploadShowAll?uploadIssues:uploadRows;
  const exportCoords=(format)=>downloadCoordinateExport(buildCoordinateExport(active,format,{title:`Dark Cat CRM · сессия №${String(session?.sessionNumber||0).padStart(4,'0')}`,fileNameBase:`dark-cat-${String(session?.sessionNumber||0).padStart(4,'0')}`}));
  const isBuffering=mode==='buffering'||folderImport?.status==='adding';
  return <section className="processing-workflow" data-processing-step={current}>
    <header className="processing-header"><p className="page-eyebrow">Обработка фото · сессия №{String(session?.sessionNumber||0).padStart(4,'0')}</p><h1>Command Desk</h1><p>Один шаг — одна рабочая задача. Данные остаются в текущей сессии.</p></header>
    <div className="processing-mobile-stepper"><strong>Шаг {PROCESSING_STEPS.findIndex((step)=>step.id===current)+1} из {PROCESSING_STEPS.length} · {PROCESSING_STEPS.find((step)=>step.id===current)?.label}</strong><select value={current} disabled={isBusy} onChange={(event)=>go(event.target.value)} aria-label="Перейти к этапу обработки">{PROCESSING_STEPS.map((step)=><option key={step.id} value={step.id} disabled={!canEnterProcessingStep(step.id,r,wf.completed,wf.stale)}>{step.label}{wf.stale.includes(step.id)?' · обновить':''}</option>)}</select></div>
    <Steps className="processing-stepper" size="small" type="navigation" responsive current={PROCESSING_STEPS.findIndex((step)=>step.id===current)} onChange={(index)=>go(PROCESSING_STEPS[index]?.id)} items={PROCESSING_STEPS.map((step)=>({ title: step.label, description: wf.stale.includes(step.id)?'обновить':undefined, disabled: isBusy||!canEnterProcessingStep(step.id,r,wf.completed,wf.stale), status: current===step.id?'process':wf.stale.includes(step.id)?'error':wf.completed.includes(step.id)?'finish':'wait' }))} />
    {wf.stale.includes(current)&&<aside className="notice notice-warning processing-stale"><strong>Этап требует обновления.</strong> Изменились более ранние данные; повторите действие этого шага.</aside>}
    {current==='photos'&&<section className="processing-surface"><div className="processing-section-heading"><div><p className="page-eyebrow">Шаг 1</p><h2>Фотографии</h2><p>Выберите фотографии или физическую папку.</p></div><strong>{r.counts.stable} принято</strong></div><UploadDropzone photos={photos} isBusy={isBusy} isBuffering={isBuffering} onFiles={props.onFiles} onFolderFiles={props.onFolderFiles} onPickFolder={props.onPickFolder} onDropItems={props.onDropItems} onCancelFolderImport={props.onCancelFolderImport} folderImport={folderImport}/>{isBuffering&&<LoadingState title="Подготовка фотографий">Создаются стабильные копии и миниатюры.</LoadingState>}{errors.length>0&&<div className="processing-issue-summary"><strong>Ошибки входных файлов</strong>{errors.map((e)=><p key={e}>{e}</p>)}</div>}{photos.length>0&&<><div className="processing-compact-summary"><span>Файлов: <strong>{photos.length}</strong></span><span>Буфер: <strong>{r.counts.stable}</strong></span><span>Папка: <strong>{folderImport?.report?.folderName||'—'}</strong></span></div><div className="processing-selected-files">{photos.map((p)=><div key={p.id}><span><strong>Фото {p.number}</strong> <small>{p.displayFileName||p.fileName}</small></span><button type="button" className="button-secondary compact-button" disabled={isBusy} onClick={()=>props.onRemovePhoto?.(p.id)}>Удалить</button></div>)}</div></>}<div className="processing-primary"><button type="button" disabled={!canAdvanceProcessingStep('photos',r)||isBusy} onClick={advance}>Далее: распознавание</button></div></section>}
    {current==='recognition'&&<section className="processing-surface"><div className="processing-section-heading"><div><p className="page-eyebrow">Шаг 2</p><h2>Распознавание</h2><p>Индекс и координаты. Проблемы — первыми.</p></div><div className="processing-metrics"><strong>{r.counts.recognized}/{r.counts.total}</strong><span>{r.counts.attention} внимания</span></div></div><div className="processing-secondary-actions"><button type="button" className="button-secondary" disabled={isBusy||!r.photos} onClick={runRecognition}>{isBusy?'Распознавание…':r.recognition?'Повторить распознавание':'Запустить распознавание'}</button>{recognitionIssues.length>0&&<button type="button" className="button-secondary" onClick={()=>setRecognitionShowAll((v)=>!v)}>{recognitionShowAll?`Только проблемы ${recognitionIssues.length}`:`Показать все ${rows.length}`}</button>}</div><div className="processing-table"><div className="processing-table-head"><span>Фото</span><span>Индекс</span><span>Координаты</span><span>Статус</span><span/></div>{visibleRows.map((p)=><div key={p.id} className={`processing-row${attention(p)?' is-attention':''}`}><span className="processing-photo-cell">{p.thumbnailDataUrl&&<img src={p.thumbnailDataUrl} alt=""/>}<strong>Фото {p.number}</strong><small>{p.displayFileName||p.fileName}</small></span><span>{p.indexFromOcr||'—'}</span><span>{p.coordinates?`${p.coordinates.latitude}, ${p.coordinates.longitude}`:'не найдены'}</span><span><StatusChip tone={attention(p)?'warning':'success'}>{p.coordinateQuality||p.gpsStatus||'ожидает'}</StatusChip></span><span><button type="button" className="button-secondary compact-button" onClick={()=>openDossier(p.id,'recognition')}>Открыть досье</button></span></div>)}</div><div className="processing-primary"><button type="button" disabled={!canAdvanceProcessingStep('recognition',r)||isBusy} onClick={advance}>Далее: карта и точки</button></div></section>}
    {current==='map'&&<section className="processing-surface processing-map-step"><div className="processing-section-heading"><div><p className="page-eyebrow">Шаг 3</p><h2>Карта и точки</h2><p>Геометрия, конфликты и ACTIVE/RESERVE. Рекомендация не применяется автоматически.</p></div><strong>{recommendation?.conflictCount||0} конфликтов</strong></div><div className="processing-secondary-actions"><button type="button" className="button-secondary" onClick={()=>exportCoords('gpx')}>GPX</button><button type="button" className="button-secondary" onClick={()=>exportCoords('kml')}>KML</button><button type="button" className="button-secondary" onClick={()=>exportCoords('geojson')}>GeoJSON</button></div><MapPanel photos={photos} thresholdMeters={thresholdMeters} providerSettings={providerSettings} mapLayerId={mapLayerId} onMapLayerChange={props.onMapLayerChange} recommendation={recommendation} onApplyRecommendation={props.onApplyRecommendation} onToggleReserve={toggleReserve} commandDeskMode onOpenDossier={(id)=>openDossier(id,'map')}/>{(recommendation?.conflictCount||0)>0&&<aside className="notice notice-warning"><strong>Есть нерешённые конфликты.</strong> Продолжение возможно только явным подтверждением оператора.</aside>}<div className="processing-primary"><button type="button" disabled={!r.canEnterMap||isBusy} onClick={advance}>{(recommendation?.conflictCount||0)>0?'Подтвердить и продолжить':'Далее: очистка и загрузка'}</button></div></section>}
    {current==='upload'&&<section className="processing-surface"><div className="processing-section-heading"><div><p className="page-eyebrow">Шаг 4</p><h2>Очистка и загрузка</h2><p>Только ACTIVE-фотографии: cleanup, upload, ошибки и retry.</p></div><div className="processing-metrics"><strong>{r.counts.active} ACTIVE</strong><span>{r.counts.uploaded}/{r.counts.active} завершено</span></div></div>{!providerValidation?.valid&&<aside className="notice notice-warning"><strong>Провайдер не готов.</strong> {providerValidation?.error}<button type="button" className="button-secondary" onClick={props.onOpenSettings}>Настройки</button></aside>}<div className="processing-secondary-actions"><button type="button" disabled={isBusy||!providerValidation?.valid||active.length===0} onClick={runUpload}>{isBusy?'Обработка…':r.upload?'Повторить ошибки / обновить ссылки':'Очистить и загрузить'}</button>{uploadIssues.length>0&&<button type="button" className="button-secondary" onClick={()=>setUploadShowAll((v)=>!v)}>{uploadShowAll?`Только ошибки ${uploadIssues.length}`:`Показать все ${uploadRows.length}`}</button>}</div><div className="processing-upload-list">{visibleUploadRows.map((p)=><article key={p.id} className={`processing-upload-row${p.userError||p.cleanupStatus==='failed'||p.uploadStatus==='failed'?' is-error':''}`}><div><strong>Фото {p.number}</strong><small>{p.displayFileName||p.fileName}</small></div><span>cleanup: {p.cleanupStatus||'idle'}</span><span>upload: {p.uploadStatus||'idle'}</span><span>{p.uploadResult?.links?.length||0} ссылок</span><button type="button" className="button-secondary compact-button" onClick={()=>openDossier(p.id,'upload')}>Досье</button></article>)}</div><div className="processing-primary"><button type="button" disabled={!canAdvanceProcessingStep('upload',r)||isBusy} onClick={advance}>Далее: результат</button></div></section>}
    {current==='result'&&<section className="processing-surface"><div className="processing-section-heading"><div><p className="page-eyebrow">Шаг 5</p><h2>Результат</h2><p>Оформите и сохраните результат текущей сессии.</p></div><strong>{r.counts.links} готовых ссылок</strong></div><ResultsSummary photos={photos} session={session} onClear={props.onClearResult} onSessionChange={props.onSessionChange} showCoordinateExport={false}/><div className="processing-primary"><button type="button" disabled={!r.result||isBusy} onClick={()=>props.onSaveSession?.()}>Сохранить сессию</button></div></section>}
    <PhotoDossier open={dossier.open} photo={selected} context={dossier.context} isBusy={isBusy} onClose={()=>setDossier((d)=>({...d,open:false}))} onApplyIndex={applyIndex} onApplyCoordinates={applyCoords} onSwapCoordinates={swap} onToggleReserve={toggleReserve}/>
  </section>;
}
